version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
          name: Add server to known hosts
          command: |
            ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts
      - run:
          name: Build and start the app
          command: |
            ssh "$USER"@"$IP_ADDRESS" << 'EOF'
            PORT=8080
            set -e
            cd wedding
            git pull
            nvm use 12
            npm ci
            npm run build
            PROCESS_ID=$( lsof -i :"$PORT" -t )
            echo "Killing process $PROCESS_ID"
            kill $PROCESS_ID
            ERROR_FILE="./process.err"
            LOG_FILE="./process.out"
            rm "$ERROR_FILE"
            npx serve ./build -p "$PORT" > "$LOG_FILE" 2> "$ERROR_FILE" < /dev/null &
            sleep 15
            if [ -s "$ERROR_FILE" ]; then
              cat "$LOG_FILE"
              cat "$ERROR_FILE"
              exit 1
            else 
              cat "$LOG_FILE"
              netstat -tulpn | grep "$PORT"
              exit
            fi
            EOF
workflows:
  version: 2
  release:
    jobs:
      - deploy

